name: CI - Lint, Test, Sonar, Build, Scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Code 🔎
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: true


      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache-dependency-path: requirements.txt
        

      - name: Create virtual environment
        run: |
            python -m venv venv
            source venv/bin/activate
            echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
            echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install pylint

      - name: Run pylint & enforce score
        run: |
            chmod +x scripts/check_pylint_score.sh
            ./scripts/check_pylint_score.sh 8.0

  test:
    name: Run Tests with Coverage 🧪
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache-dependency-path: requirements.txt

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          echo "🧪 Running unit tests with coverage analysis..."
          pytest test_app.py -v --cov=app --cov-report=term --cov-report=xml --cov-report=html
          echo "✅ Tests completed with coverage analysis!"

      - name: Check coverage threshold
        run: |
          chmod +x scripts/check_coverage_threshold.sh
          ./scripts/check_coverage_threshold.sh 75

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-reports
          path: |
            coverage.xml
            htmlcov/
          retention-days: 30

      - name: Display coverage summary
        run: |
          echo "📊 Coverage Summary:"
          echo "==================="
          python -c "
          import xml.etree.ElementTree as ET
          try:
              tree = ET.parse('coverage.xml')
              root = tree.getroot()
              line_rate = float(root.attrib.get('line-rate', 0)) * 100
              branch_rate = float(root.attrib.get('branch-rate', 0)) * 100
              print(f'Line Coverage: {line_rate:.1f}%')
              print(f'Branch Coverage: {branch_rate:.1f}%')
          except:
              print('Could not parse coverage.xml')
          "

  sonar:
    name: SonarQube Analysis with Coverage 📈
    runs-on: self-hosted
    needs: test
    env:
      SONAR_PROJECT_KEY: devops-lab-1
      SONAR_PROJECT_NAME: DevOps Lab Project
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_HOST_URL: http://localhost:9000
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download coverage reports
        uses: actions/download-artifact@v4
        with:
          name: coverage-reports

      - name: Run SonarQube Scan with Coverage
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://localhost:9000

      - name: Wait & check SonarQube quality gate
        run: |
          chmod +x scripts/check_sonar_quality_gate.sh
          ./scripts/check_sonar_quality_gate.sh devops-lab-1 180

      - name: Display SonarQube metrics
        if: always()
        run: |
          echo "🎯 SonarQube Analysis Complete!"
          echo "================================"
          echo "📊 Check your SonarQube dashboard at: $SONAR_HOST_URL"
          echo "🔍 Project: $SONAR_PROJECT_KEY"
          echo "📈 Coverage data has been integrated with code quality metrics"

  build-and-scan:
    name: Build & Scan Image 🛠️🔒
    runs-on: ubuntu-latest
    needs: sonar
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Build Docker image
        run: |
          docker build -t test-app:latest .

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: test-app:latest
          format: 'table'
          output: 'trivy-results.txt'
          severity: 'CRITICAL,HIGH'

      - name: Display Trivy scan results
        if: always()
        run: |
          echo "🔍 Security Scan Results for test-app:latest"
          echo "============================================="
          if [ -f trivy-results.txt ]; then
            cat trivy-results.txt
            
            # Count vulnerabilities
            CRITICAL=$(grep -c "CRITICAL" trivy-results.txt || echo "0")
            HIGH=$(grep -c "HIGH" trivy-results.txt || echo "0")
            
            echo ""
            echo "📊 Summary:"
            echo "  🔴 Critical: $CRITICAL"
            echo "  🟠 High: $HIGH"
            
            if [ "$CRITICAL" -gt 0 ] || [ "$HIGH" -gt 0 ]; then
              echo "⚠️  Security vulnerabilities detected!"
              echo "🔧 Consider updating base images or dependencies"
            else
              echo "✅ No critical or high severity vulnerabilities found!"
            fi
          else
            echo "❌ Trivy scan results not found"
          fi

